#!/usr/bin/env bash

docker-compose exec mysql bash -c 'mysql -uroot -hmysql fc < /dumps/init.sql'
docker-compose exec php ./yii migrate --interactive=0
#docker-compose exec php ./yii migrate/fresh --interactive=0
